version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  grafana:
    ports:
      - "3000"

