version: '3.4'

services:
  books.app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
      
  books.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  grafana:
    ports:
      - "3000"
      